# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [2]:
# Your code here
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([7,8,9])

A @ (B+C) == (A@B + A@C)

True

## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [7]:
# Your code here 
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.array([[9,10], [11,12]])

A @ (B @ C) == (A @ B) @ C

array([[ True,  True],
       [ True,  True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [8]:
# Your code here 
A @ B == B @ A

array([[False, False],
       [False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [9]:
# Your code here 
x = np.array([1,2,3])
y = np.array([4,5,6])

x.T @ y == y.T @ x

True

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [11]:
# Your code here 
(A @ B).T == B.T @ A.T

array([[ True,  True],
       [ True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 